server:
  port: 10002


spring:
  application:
    name: eureka-client

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka

  instance:
    instance-id: spring-cloud-provider-10002
#    prefer-ip-address: true


