
server:
  port: 10003


spring:
  application:
    name: eureka-openfeign

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka/

  instance:
    instance-id: spring-cloud-provider-openfeign
#    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
